### ISSUE TITLE
timeout的问题

### ISSUE THREAD

**Issue by Jack-Tian** [NetEase/AutomatorX#65]
## What steps will reproduce the problem?
举例：
import atx
d = atx.connect()
d.adb_shell("monkey -p com.android.contacts -v -v -v --throttle 500 --ignore-timeouts --ignore-crashes --ignore-security-exceptions 1500",timeout=1)

## What is the expected output?
报错信息最后为TypeError: __init__() takes at least 3 arguments (2 given)，为啥是错误类型是TypeError？

## What do you see instead?
报错信息最后为TypeError: __init__() takes at least 3 arguments (2 given)，为啥是错误类型是TypeError？

## Do you have any log or screenshots?
Traceback (most recent call last):
  File "D:\APPIOT\Appiot\testtimeout.py", line 5, in <module>
    d.adb_shell("monkey -p com.android.contacts -v -v -v --throttle 500 --ignore-timeouts --ignore-crashes --ignore-security-exceptions 1500",
timeout=1)
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 336, in adb_shell
    return self.adb_cmd(['shell'] + [command], **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 320, in adb_cmd
    return self.adb_device.run_cmd(*list(command), **kwargs)
  File "C:\Python27\lib\site-packages\atx\adbkit\device.py", line 53, in run_cmd
    return p.communicate(timeout=timeout)[0].replace('\r\n', '\n')
  File "C:\Python27\lib\site-packages\subprocess32.py", line 927, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Python27\lib\site-packages\subprocess32.py", line 1190, in _communicate
    raise TimeoutExpired(self.args)
TypeError: __init__() takes at least 3 arguments (2 given)

**Comment by codeskyblue** [comment]
这个是subprocess32 在windows上才会出现的错误，这个库的作者平常只在linux或mac上工作，windows的错误根本不管，所以才会有这个TypeError

这个错误处理起来有点棘手

**Comment by Jack-Tian** [comment]
了解了，多谢！
