### ISSUE TITLE
record doesn't work in osx

### ISSUE THREAD

**Issue by wyp0011** [NetEase/AutomatorX#66]
$ python -m atx record
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/atx/__main__.py", line 140, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/atx/__main__.py", line 137, in main
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/atx/__main__.py", line 42, in _inner
    __import__(module_path)
  File "/usr/local/lib/python2.7/site-packages/atx/cmds/record.py", line 12, in <module>
    import win32api
ImportError: No module named win32api

**Comment by codeskyblue** [comment]
@wuxc 这个功能估计很快就要被另外一个新的IDE取代了

**Comment by wyp0011** [comment]
@codeskyblue 没找到代码里面那一部分import win32api，可否告知一下？

**Comment by codeskyblue** [comment]
你先升级下atx到最新的版本吧

**Comment by wyp0011** [comment]
已经升级了，还是不行。。

**Comment by codeskyblue** [comment]
The lastest version has not use lib win32api.
